In [1]:
from my_functions import text_reader , leng_sentences , polarity_sentences_list , subjectivity_sentences_list, create_chapter_numbers, split_by_chapter_number, remove_indexed_values, create_chapter_data_frame, book_df, syntax_length
import pandas as pd
from textblob import TextBlob

# Import Book 1

In [2]:
book1 = text_reader("/Users/BaileyDanielson/Documents/Python/IHC.txt")

# Split Book 1 by Section

In [3]:
chapters = split_by_chapter_number(book1)

In [4]:
len(chapters)

268

In [5]:
new_chapters = remove_indexed_values(chapters , 0)

In [6]:
new_chapters.pop(267, None)

['The End\n \n \n \n \n \n \n \n \n \n \n \n \n \n \x0cJ. M. Coetzee was born in Cape Town, South Africa, in 1940 and educated in\n South Africa and the United States.',
 'His first work of fiction was Dusklands\n (1974).',
 'This was followed by In The Heart of The Country (1977), which\n won the premier South African literary award, the CNA Prize; Waiting for the\n Barbarians (1980), which was awarded the CNA Prize, the Geoffrey Faber\n Memorial Prize and the James Tail Black Memorial Prize; Life & Times of\n Michael K (1983), which won the 1983 Booker Prize and the 1985 Prix\n Etranger Femina; Foe (1986); White Writing (1988), a collection of essays;\n and Age of Iron (1990) which won the 1990 Sunday Express Book of the\n Year Award.',
 'J. M. Coetzee was winner of the Jerusalem Prize for 1987.',
 'Many of\n his books are published by Penguin.',
 'His other works include translations,\n linguistic studies and literary criticism.',
 'He is, at present, Professor of General\n Literature at the University of Cape Town.',
 'All of his novels have received the\n highest critical, acclaim; writing for the Sunday Times, Victoria Glendimung\n said, "It is hard to convey just what Coetzee\'s special quality is.',
 'His writing\n gives off whiffs of Conrad, of Nabokov, of Golding, of the Paul Theroux of\n The Mosquito Coast.',
 'And Bernard Levin has described him as an artist of\n weight and depth that put him in a category beyond ordinary comparison.']

In [7]:
len(new_chapters)

267

# Create Data Frame for Book 1

In [8]:
df = pd.DataFrame()

In [9]:
test_chapter = new_chapters[3]
test_chapter

['She is the new wife, therefore the old one is dead.',
 'The old wife was\n my mother, but died so many years ago that I barely recall her.',
 'I must have\n been very young when she died, perhaps only a newborn babe.',
 'From one of\n the farthest oubliettes of memory I extract a faint grey image, the image of a\n faint grey frail gentle loving mother huddled on the floor, one such as any girl\n in my position would be likely to make up for herself.']

In [10]:
chapter_4 = create_chapter_data_frame(new_chapters[4], 4, "In the Heart of the Country", "J.M. Coetzee")

In [11]:
new_chapters.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266])

In [12]:
new_chapters[7]

['Night falls, and my father and his new wife cavort in the bedroom.',
 'Hand in hand they stroke her womb, watching for it to flicker and blossom.',
 'They twine; she laps him in her flesh; they chuckle and moan.',
 'These are fair\n times for them.']

In [13]:
df_book1 = (book_df(new_chapters, "In the Heart of the Country", "J.M. Coetzee"))

In [14]:
sentence1 = list(df_book1["Sentence"])

In [15]:
len(sentence1)

3521

In [16]:
s_index1 = list(range(0, len(sentence1)))
df_book1["Index"] = s_index1

In [17]:
pols1 = polarity_sentences_list(sentence1)
print(pols1[:20])

[0.0, 0.13636363636363635, -0.225, 0.0, -0.11507936507936507, 0.5, 0.012500000000000011, 0.0, 0.11249999999999999, -0.11666666666666667, -0.05454545454545454, 0.0, 0.13636363636363635, -0.07121212121212121, -0.16666666666666666, 0.12222222222222223, 0.0, 0.0, 0.09999999999999999, 0.0]

In [18]:
df_book1["Polarity"] = pols1

In [19]:
subs1 = subjectivity_sentences_list(sentence1)
print(subs1[:20])

[0.0, 0.45454545454545453, 0.5, 1.0, 0.2396825396825397, 0.5, 0.625, 0.0, 0.775, 0.20833333333333331, 0.3515151515151515, 0.0, 0.45454545454545453, 0.6181818181818182, 0.43333333333333335, 0.3333333333333333, 0.0, 0.0, 0.35000000000000003, 0.0]

In [20]:
df_book1["Subjectivity"] = subs1

In [21]:
word_count1 = syntax_length(sentence1)
df_book1["Word_Count"] = word_count1

In [22]:
df_book1.head(30)

,Sentence,Section,Book_Title,Author,Index,Polarity,Subjectivity,Word_Count
0,Coetzee\n In the Heart of the Country.,0,In the Heart of the Country,J.M. Coetzee,0,0.000000,0.000000,7
1,Today my father brought home his new bride.,1,In the Heart of the Country,J.M. Coetzee,1,0.136364,0.454545,8
2,They came clip-clop across\n the flats in a do...,1,In the Heart of the Country,J.M. Coetzee,2,-0.225000,0.500000,25
3,Or perhaps they were drawn by two\n plumed don...,1,In the Heart of the Country,J.M. Coetzee,3,0.000000,1.000000,13
4,My father wore his black swallowtail\n coat an...,1,In the Heart of the Country,J.M. Coetzee,4,-0.115079,0.239683,24
5,More detail I cannot give unless I begin to\n ...,1,In the Heart of the Country,J.M. Coetzee,5,0.500000,0.500000,15
6,"I was in my room, in the emerald semi-\n dark ...",1,In the Heart of the Country,J.M. Coetzee,6,0.012500,0.625000,32
7,I am the one who stays\n in her room reading o...,1,In the Heart of the Country,J.M. Coetzee,7,0.000000,0.000000,15
8,"The colonies are full of\n girls like that, bu...",1,In the Heart of the Country,J.M. Coetzee,8,0.112500,0.775000,16
9,My father is the one who\n paces the floorboar...,1,In the Heart of the Country,J.M. Coetzee,9,-0.116667,0.208333,20
10,"And then, for a third, there is the new wife, ...",1,In the Heart of the Country,J.M. Coetzee,10,-0.054545,0.351515,14
11,Those are the\n antagonists.,1,In the Heart of the Country,J.M. Coetzee,11,0.000000,0.000000,4
12,The new wife.,2,In the Heart of the Country,J.M. Coetzee,12,0.136364,0.454545,3
13,The new wife is a lazy big-boned voluptuous fe...,2,In the Heart of the Country,J.M. Coetzee,13,-0.071212,0.618182,15
14,Her eyes are black and shrewd like\n two berri...,2,In the Heart of the Country,J.M. Coetzee,14,-0.166667,0.433333,13
15,She is a big woman with fine wrists\n and long...,2,In the Heart of the Country,J.M. Coetzee,15,0.122222,0.333333,13
16,She eats her food with relish.,2,In the Heart of the Country,J.M. Coetzee,16,0.000000,0.000000,6
17,She sleeps and\n eats and lazes.,2,In the Heart of the Country,J.M. Coetzee,17,0.000000,0.000000,6
18,She sticks out her long red tongue and licks t...,2,In the Heart of the Country,J.M. Coetzee,18,0.100000,0.350000,16
19,"""Ah, I like that!""",2,In the Heart of the Country,J.M. Coetzee,19,0.000000,0.000000,4
20,"she says, and smiles and rolls her eyes.",2,In the Heart of the Country,J.M. Coetzee,20,0.000000,0.000000,8
21,"I\n watch her mouth, mesmerized.",2,In the Heart of the Country,J.M. Coetzee,21,0.000000,0.000000,5
22,Then she turns on me the wide smiling mouth\n ...,2,In the Heart of the Country,J.M. Coetzee,22,-0.133333,0.416667,14
23,I cannot easily sustain her smile.,2,In the Heart of the Country,J.M. Coetzee,23,0.366667,0.466667,6
24,We are not a\n happy family together.,2,In the Heart of the Country,J.M. Coetzee,24,-0.400000,1.000000,7
25,"She is the new wife, therefore the old one is ...",3,In the Heart of the Country,J.M. Coetzee,25,0.012121,0.351515,11
26,"The old wife was\n my mother, but died so many...",3,In the Heart of the Country,J.M. Coetzee,26,0.216667,0.266667,17
27,"I must have\n been very young when she died, p...",3,In the Heart of the Country,J.M. Coetzee,27,0.065000,0.760000,14
28,From one of\n the farthest oubliettes of memor...,3,In the Heart of the Country,J.M. Coetzee,28,-0.037500,0.681250,44
29,"My father's first wife, my mother, was a frail...",4,In the Heart of the Country,J.M. Coetzee,29,0.350000,0.694444,20

# Import Book 2

In [23]:
book2 = "/Users/BaileyDanielson/Documents/Python/Shadow_Lines.txt"

# Split Book 2 by Sections

In [26]:
numbers = create_chapter_numbers(book2, ["Coming Home" , "Going Away"])
sections = split_by_chapter_number(numbers)
new_sections = remove_indexed_values(sections, 0)

# Create Data Frame for Book 2

In [27]:
new_sections.keys()

dict_keys([0, 1, 2])

In [28]:
df_book2 = (book_df(new_sections, "Shadow Lines", "Amitav Ghosh"))

In [29]:
sentence2 = list(df_book2["Sentence"])

In [30]:
s_index2 = list(range(0, len(sentence2)))
df_book2["Index"] = s_index2

In [31]:
pols2 = polarity_sentences_list(sentence2)
print(pols2[:20])

[0.0, 0.0, 0.1, 0.05, -0.371875, 0.0, -0.05000000000000001, 0.0, 0.3333333333333333, 0.005208333333333329, 0.12916666666666665, 0.0, 0.43333333333333335, -0.1, 0.0, 0.0, -0.12916666666666668, -0.3333333333333333, 0.0, -0.2]

In [32]:
df_book2["Polarity"] = pols2

In [33]:
subs2 = subjectivity_sentences_list(sentence2)
print(subs2[:20])

[0.0, 0.0, 0.75, 0.5, 0.575, 0.75, 0.4125, 0.0, 0.38888888888888884, 0.27604166666666663, 0.35694444444444445, 0.0, 0.65, 0.5, 0.0, 0.1, 0.5, 0.6666666666666666, 0.0, 0.0]

In [34]:
df_book2["Subjectivity"] = subs2

In [35]:
word_count2 = syntax_length(sentence2)
df_book2["Word_Count"] = word_count2

In [36]:
df_book2.head(30)

,Sentence,Section,Book_Title,Author,Index,Polarity,Subjectivity,Word_Count
0,Going Away.,1,Shadow Lines,Amitav Ghosh,0,0.000000,0.000000,2
1,"In 1939, thirteen years before I was born, my ...",1,Shadow Lines,Amitav Ghosh,1,0.000000,0.000000,22
2,It startles me now to discover how readily the...,1,Shadow Lines,Amitav Ghosh,2,0.100000,0.750000,40
3,"But still, from as far back as I can remember,...",1,Shadow Lines,Amitav Ghosh,3,0.050000,0.500000,45
4,Perhaps it was merely because I knew her very ...,1,Shadow Lines,Amitav Ghosh,4,-0.371875,0.575000,17
5,"That explanation seems likely enough, but I kn...",1,Shadow Lines,Amitav Ghosh,5,0.000000,0.750000,12
6,The truth is that I did not want to think of h...,1,Shadow Lines,Amitav Ghosh,6,-0.050000,0.412500,53
7,"Mayadebi was twenty-nine when they left, and T...",1,Shadow Lines,Amitav Ghosh,7,0.000000,0.000000,10
8,"Over the years, although I cannot remember whe...",1,Shadow Lines,Amitav Ghosh,8,0.333333,0.388889,47
9,I remember trying very hard to imagine him\n b...,1,Shadow Lines,Amitav Ghosh,9,0.005208,0.276042,42
10,"It wasn’t easy, for to me he looked old, impos...",1,Shadow Lines,Amitav Ghosh,10,0.129167,0.356944,38
11,"In the end, since I had nothing to go on, I ha...",1,Shadow Lines,Amitav Ghosh,11,0.000000,0.000000,19
12,"But my grandmother, when I asked her, was very...",1,Shadow Lines,Amitav Ghosh,12,0.433333,0.650000,13
13,"She shook her head firmly, looking up from her...",1,Shadow Lines,Amitav Ghosh,13,-0.100000,0.500000,23
14,My grandmother didn’t approve of Tridib.,1,Shadow Lines,Amitav Ghosh,14,0.000000,0.000000,6
15,"He’s a loafer and a wastrel, I would sometimes...",1,Shadow Lines,Amitav Ghosh,15,0.000000,0.100000,26
16,"To me, she would only allow herself to say wit...",1,Shadow Lines,Amitav Ghosh,16,-0.129167,0.500000,31
17,"It didn’t sound terrible, but in fact, in my g...",1,Shadow Lines,Amitav Ghosh,17,-0.333333,0.666667,23
18,"For her, time was\n like a toothbrush: it went...",1,Shadow Lines,Amitav Ghosh,18,0.000000,0.000000,14
19,I asked her once what happened to wasted time.,1,Shadow Lines,Amitav Ghosh,19,-0.200000,0.000000,9
20,"She tossed her small silvery head, screwed up\...",1,Shadow Lines,Amitav Ghosh,20,-0.150000,0.400000,17
21,"As for herself, she had been careful to rid ou...",1,Shadow Lines,Amitav Ghosh,21,-0.104167,0.541667,23
22,No chessboard nor any pack of\n cards ever cam...,1,Shadow Lines,Amitav Ghosh,22,0.000000,0.833333,50
23,In our flat we all worked hard at whatever we ...,1,Shadow Lines,Amitav Ghosh,23,-0.158333,0.333333,42
24,Our time wasn’t given the slightest opportunit...,1,Shadow Lines,Amitav Ghosh,24,0.000000,0.000000,10
25,That was why I loved to listen to Tridib: he n...,1,Shadow Lines,Amitav Ghosh,25,0.700000,0.800000,21
26,Sometimes Tridib would drop in to see us witho...,1,Shadow Lines,Amitav Ghosh,26,0.000000,0.000000,10
27,"My grandmother, for all her disapproval of him...",1,Shadow Lines,Amitav Ghosh,27,0.368333,0.756667,57
28,"But of course, she knew, though she wouldn’t a...",1,Shadow Lines,Amitav Ghosh,28,0.200000,0.200000,19
29,The truth was that his digestion was a mess;\n...,1,Shadow Lines,Amitav Ghosh,29,-0.337500,0.587500,26

# Merge df_book 1 & df_book 2

In [37]:
# final df = df_book1.append(df_book2, ignore_index = True)

In [38]:
final_df = df_book1.append(df_book2, ignore_index = True)

In [39]:
final_df.head(10)

,Sentence,Section,Book_Title,Author,Index,Polarity,Subjectivity,Word_Count
0,Coetzee\n In the Heart of the Country.,0,In the Heart of the Country,J.M. Coetzee,0,0.000000,0.000000,7
1,Today my father brought home his new bride.,1,In the Heart of the Country,J.M. Coetzee,1,0.136364,0.454545,8
2,They came clip-clop across\n the flats in a do...,1,In the Heart of the Country,J.M. Coetzee,2,-0.225000,0.500000,25
3,Or perhaps they were drawn by two\n plumed don...,1,In the Heart of the Country,J.M. Coetzee,3,0.000000,1.000000,13
4,My father wore his black swallowtail\n coat an...,1,In the Heart of the Country,J.M. Coetzee,4,-0.115079,0.239683,24
5,More detail I cannot give unless I begin to\n ...,1,In the Heart of the Country,J.M. Coetzee,5,0.500000,0.500000,15
6,"I was in my room, in the emerald semi-\n dark ...",1,In the Heart of the Country,J.M. Coetzee,6,0.012500,0.625000,32
7,I am the one who stays\n in her room reading o...,1,In the Heart of the Country,J.M. Coetzee,7,0.000000,0.000000,15
8,"The colonies are full of\n girls like that, bu...",1,In the Heart of the Country,J.M. Coetzee,8,0.112500,0.775000,16
9,My father is the one who\n paces the floorboar...,1,In the Heart of the Country,J.M. Coetzee,9,-0.116667,0.208333,20

In [40]:
final_df.to_csv("/Users/BaileyDanielson/Documents/Python/NLP_Practice/final_df.csv" , index = False)

In [41]:
final_sentences = list(final_df["Sentence"])

In [42]:
clean_sentences = [s.replace('\n', ' ') for s in final_sentences]

In [43]:
final_df["Sentence"] = clean_sentences

In [44]:
final_df.head()

,Sentence,Section,Book_Title,Author,Index,Polarity,Subjectivity,Word_Count
0,Coetzee In the Heart of the Country.,0,In the Heart of the Country,J.M. Coetzee,0,0.000000,0.000000,7
1,Today my father brought home his new bride.,1,In the Heart of the Country,J.M. Coetzee,1,0.136364,0.454545,8
2,They came clip-clop across the flats in a dog...,1,In the Heart of the Country,J.M. Coetzee,2,-0.225000,0.500000,25
3,Or perhaps they were drawn by two plumed donk...,1,In the Heart of the Country,J.M. Coetzee,3,0.000000,1.000000,13
4,My father wore his black swallowtail coat and...,1,In the Heart of the Country,J.M. Coetzee,4,-0.115079,0.239683,24

In [45]:
final_df.to_csv("/Users/BaileyDanielson/Documents/Python/NLP_Practice/final_df.csv" , index = False)